<a href="https://colab.research.google.com/github/Reina-creator/MSSP607-GitHub/blob/main/WeeklyModules/Week06" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

This notebook uses a lambda function to take the Student Performance DataFrame and return a new DataFrame containing students whose total scores are greater than or equal to the average total score.

In [2]:
import pandas as pd

students = pd.read_csv("Student Performance Data.csv")

students.head()

,gender,race/ethnicity,parental level of education,lunch,math score,reading score,writing score,total score,test preparation course,admission prospect
0,female,group B,bachelor's degree,standard,72,72,74,218,none,medium
1,female,group C,some college,standard,69,90,88,247,completed,high
2,female,group B,master's degree,standard,90,95,93,278,none,high
3,male,group A,associate's degree,free/reduced,47,57,44,148,none,low
4,male,group C,some college,standard,76,78,75,229,none,high

In [3]:
print("Number of rows and columns:", students.shape)
print("Average total score:", students["total score"].mean())

Number of rows and columns: (1000, 10)
Average total score: 203.312

In [4]:
above_average = lambda data: data[
    data["total score"] >= data["total score"].mean()
].copy()

above_average_students = above_average(students)

above_average_students.head()

,gender,race/ethnicity,parental level of education,lunch,math score,reading score,writing score,total score,test preparation course,admission prospect
0,female,group B,bachelor's degree,standard,72,72,74,218,none,medium
1,female,group C,some college,standard,69,90,88,247,completed,high
2,female,group B,master's degree,standard,90,95,93,278,none,high
4,male,group C,some college,standard,76,78,75,229,none,high
5,female,group B,associate's degree,standard,71,83,78,232,none,high

In [5]:
print("Returned object type:", type(above_average_students))
print("Number of students:", len(above_average_students))

above_average_students

Returned object type: <class 'pandas.core.frame.DataFrame'>
Number of students: 526

,gender,race/ethnicity,parental level of education,lunch,math score,reading score,writing score,total score,test preparation course,admission prospect
0,female,group B,bachelor's degree,standard,72,72,74,218,none,medium
1,female,group C,some college,standard,69,90,88,247,completed,high
2,female,group B,master's degree,standard,90,95,93,278,none,high
4,male,group C,some college,standard,76,78,75,229,none,high
5,female,group B,associate's degree,standard,71,83,78,232,none,high
...,...,...,...,...,...,...,...,...,...,...
992,female,group D,associate's degree,free/reduced,55,76,76,207,none,medium
993,female,group D,bachelor's degree,free/reduced,62,72,74,208,none,medium
995,female,group E,master's degree,standard,88,99,95,282,completed,high
998,female,group D,some college,standard,68,78,77,223,completed,high
999,female,group D,some college,free/reduced,77,86,86,249,none,high